#%RAML 1.0 Trait
headers: 
      x-correlation-id:
        description: Correlation id to maintain over APIs
        type: string
        required: true
        example: "39c9547f08d6498194391d7b81811bc1"
        